[project]
name = "SlaterGPU"
version = "0.1.0"
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64"]

[tasks]
clean = "rm -rf build"
build = "cmake --build build"

[tasks.configure]
cmd = "cmake -Bbuild"
depends_on = ["clean"]
[tasks.configure.env]
CXX = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvc++"
CC = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvc"

[system-requirements]
linux = "3.10"
libc = { family="glibc", version="2.17" }

[dependencies]
# gcc = ">=13.2.0,<13.3"
# cuda = ">=12,<13"
# cuda-nvcc = ">=12,<13"
cuda-toolkit = ">=12,<13"

[build-dependencies]
cmake = ">=3.21.0,<4"
# openmpi = ">=5.0.3,<5.1"
openmpi = "=3.1"
openmpi-mpicc = "=3.1"
openmpi-mpicxx = "=3.1"