[workspace]
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[package]
name = "SlaterGPU"
version = "0.1.0"

[package.build]
# backend = { name = "pixi-build-cmake", version = "*" }
backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks]
slurm-job = "/export/SLURM/default/bin/srun -p zimA10 -N1 -n16 --gpus=1 --pty /bin/bash"

[tasks.clean]
description = "Remove example output files"
cwd = "examples/geom_1"
cmd = "rm -f A Ciap g pVp SENT"

[feature.pytest.tasks.test]
description = "Test SlaterGPU executable on a small molecular system"
cwd = "examples/geom_1"
cmd = "/export/SLURM/default/bin/srun -p zim2080 -N1 -n1 -c2 --gpus=1 sgpu.exe && cd .. && pytest"

[feature.pytest.tasks.test-gauss-basis]
description = "Test SlaterGPU executable including libcint on H2 with Gaussian basis"
cwd = "examples/h2_gaussian_basis"
cmd = "/export/SLURM/default/bin/srun -p zim2080 -N1 -n1 -c2 --gpus=1 sgpu.exe"

[feature.pytest.tasks.test-in-gh-action]
description = "Test SlaterGPU executable on a small molecular system in a github actions environment"
cwd = "examples/geom_1"
cmd = "sgpu.exe && cd .. && pytest"

[system-requirements]
linux = "3.10"
libc = { family="glibc", version="2.17" }

[dependencies]
cmake = ">=3.21.0,<4"
# libgcc = ">=12,<13"
SlaterGPU = {path = "."}

[package.host-dependencies]
libcint = "5.3.0.*"

[feature.pytest.dependencies]
pytest = ">=8.3.3,<9"
numpy = ">=2.1.3,<3"

[environments]
pytest = {features = ["pytest"]}
