[project]
name = "SlaterGPU"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
configure = "cmake -Bbuild"
clean = "rm -rf build"
build = "cmake --build build"

[system-requirements]
linux = "3.10"
libc = { family="glibc", version="2.17" }

[dependencies]
gcc = ">=13.2.0,<13.3"

[build-dependencies]
cmake = ">=3.21.0,<4"
# openmpi = ">=5.0.3,<5.1"
openmpi = "=3.1"
openmpi-mpicc = "=3.1"
openmpi-mpicxx = "=3.1"
