[project]
name = "SlaterGPU"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
configure = { cmd = "cmake ..", cwd = "build" , depends-on = ["make_build_dir"]}
make_build_dir = "mkdir -p build"

[system-requirements]
linux = "3.10"
libc = { family="glibc", version="2.17" }

[dependencies]

[build-dependencies]
cmake = ">=3.21.0,<4"
