[project]
name = "SlaterGPU"
version = "0.1.0"
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[tasks]
# load = "module load nvidia-sdk"
clean = "rm -rf build"
build = "cmake --build build -j 16"
test = {cmd = ["../sgpu.exe"], cwd = "build/examples/geom_1"}
start = {depends-on = ["configure", "build", "test"]}

[feature.athena]
platforms = ["linux-64"]
[feature.linux-64]
platforms = ["linux-64"]

[feature.athena.tasks]
slurm-job = "srun -p zimA10 -N1 -n16 --gpus=1 --pty /bin/bash"

[feature.athena.tasks.configure]
cmd = "cmake -Bbuild"
depends-on = ["clean"]
[feature.athena.tasks.configure.env]
LIBCINT_PATH="/home/ndmeier/libraries/libcint"
BLAS_INCLUDE_DIR="/usr/include/openblas"
OMP_NUM_THREADS="2"
NVHPC = "/export/apps/RockyOS8/nvidia_hpc/2024_249"
NVHPC_ROOT = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9"
CC = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvc"
CXX = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvc++"
FC = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvfortran"
F90 = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvfortran"
F77 = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin/nvfortran"
CPP = "cpp"
PATH = """\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/cuda/bin:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/bin:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/mpi/bin:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/extras/qd/bin:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/2024/comm_libs/mpi/bin:\
$PATH\
"""
LD_LIBRARY_PATH = """\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/cuda/lib64:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/extras/qd/lib:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/lib:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/math_libs/lib64:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nccl/lib:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nvshmem/lib:\
$LD_LIBRARY_PATH:\
/home/ndmeier/libraries/libcint/lib64\
"""
CPATH = """\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/math_libs/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nccl/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nvshmem/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/extras/qd/include/qd:\
$CPATH\
"""
C_INCLUDE_PATH = """\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/math_libs/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nccl/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nvshmem/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/extras/qd/include/qd:\
$C_INCLUDE_PATH\
"""
CPLUS_INCLUDE_PATH = """\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/math_libs/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nccl/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/comm_libs/nvshmem/include:\
/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/extras/qd/include/qd:\
$CPLUS_INCLUDE_PATH\
"""
MANPATH = "/export/apps/RockyOS8/nvidia_hpc/2024_249/Linux_x86_64/24.9/compilers/man:$MANPATH"

[system-requirements]
linux = "3.10"
libc = { family="glibc", version="2.17" }

[dependencies]
cmake = ">=3.21.0,<4"

[feature.linux-64.dependencies]
# gcc = ">=13.2.0,<13.3"
# cuda = ">=12,<13"
# cuda-nvcc = ">=12,<13"
cuda-toolkit = ">=12,<13"
# openmpi = ">=5.0.3,<5.1"
openmpi = "=3.1"
openmpi-mpicc = "=3.1"
openmpi-mpicxx = "=3.1"

[environments]
athena = {features = ["athena"]}
linux-64 = {features = ["linux-64"]}
