context:
  version: "0.1.13"

package:
  name: slatergpu
  version: ${{ version }}

source:
  path: src

build:
  number: 0

requirements:
  build:
    - cmake =4.0.3
  host:
    - libcint =5.3.0
  run:
