context:
  version: "0.1.0"

package:
  name: SlaterGPU
  version: ${{ version }}

source:
  path: src

build:
  number: 0
  # script: |
  #   PIXI_PROJECT_MANIFEST=$SRC_DIR/pixi.toml pixi run configure-athena
  #   PIXI_PROJECT_MANIFEST=$SRC_DIR/pixi.toml pixi run build
#    cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$PREFIX $SRC_DIR -DCMAKE_INSTALL_LIBDIR=lib
#    cmake --build build -j 16

requirements:
  # build:
    # - pixi
    # - cmake
  host:
    - libcint =5.3.0
  run:
    - libcint =5.3.0

  # run:
  #   - xtl >=0.7,<0.8
  # run_constraints: # (3)!
  #   - xsimd >=8.0.3,<10

# tests:
#   - package_contents:
#       include: # (4)!
#         - xtensor/xarray.hpp
#       files: # (5)!
#         - ${{ "Library" if win }}/share/cmake/xtensor/xtensorConfig.cmake
#         - ${{ "Library" if win }}/share/cmake/xtensor/xtensorConfigVersion.cmake

# about:
#   homepage: https://github.com/xtensor-stack/xtensor
#   license: BSD-3-Clause
#   license_file: LICENSE
#   summary: The C++ tensor algebra library
#   description: Multi dimensional arrays with broadcasting and lazy computing
#   documentation: https://xtensor.readthedocs.io
#   repository: https://github.com/xtensor-stack/xtensor

# extra:
#   recipe-maintainers:
#     - some-maintainer