name: Debug CI with upterm
on: [workflow_dispatch]

jobs:
  debug-session:
    runs-on: gpu
    steps:
    - uses: ./.github/workflows/slater-gpu-base.yml
    - name: Setup upterm session 
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true
