name: SlaterGPU Base

on:
  workflow_call:
    inputs:
      use-latest-pixi:
        type: boolean
        default: false

jobs:
  build:
    runs-on: gpu

    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Setup build environment
      uses: ./.github/actions/setup-build-env
      with:
        use-latest-pixi: ${{ inputs.use-latest-pixi }}

    - name: Install and test SlaterGPU
      run: |
        source ~/.pixi/envs/environment-modules/init/bash
        module load ~/work/modulefiles/nvhpc/25.1
        module list
        pixi -v install
        pixi -v run test-in-gh-action
