name: Tmate debugging
on: [workflow_dispatch]
jobs:
  explore:
    # runs-on: ubuntu-latest
    runs-on: gpu
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.41.3
        log-level: v
        # cache: true
      continue-on-error: true
    - name: Install nvhpc
      run: source .github/workflows/install_nvhpc.sh
      continue-on-error: true
    - name: Install SlaterGPU
      run: pixi install
      continue-on-error: true
    - name: Attempt to run test
      run: pixi run test-in-gh-action
      continue-on-error: true
    - name: Setup tmate session 
      uses: mxschmitt/action-tmate@v3
