name: Tmate debugging
on: [workflow_dispatch]
jobs:
  explore:
    runs-on: ubuntu-latest
    # runs-on: gpu
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3