name: Tmate debugging
on: [workflow_dispatch]
jobs:
  explore:
    # runs-on: ubuntu-latest
    runs-on: gpu
    defaults:
      run:
        shell: bash
    steps:
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.41.3
        log-level: v
        # cache: true
      continue-on-error: true
    - uses: actions/checkout@v4
    - name: Install nvhpc
      run: source .github/workflows/install_nvhpc.sh
      run: source ~/.pixi/envs/environment-modules/init/bash
      run: module load ~/work/modulefiles/nvhpc/25.1
      run: module list
      continue-on-error: true
    - name: Install SlaterGPU
      run: pixi install
      continue-on-error: true
    - name: Attempt to run test
      run: pixi run test-in-gh-action
      continue-on-error: true
    - name: Setup upterm session 
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true
    # - name: Setup tmate session 
    #   uses: mxschmitt/action-tmate@v3
